package com.esprit.minipo;


import com.esprit.minipo.gui.*;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.FlowLayout;
import java.util.Hashtable;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    public static Resources theme;
    private Resources baseEmp;

    public Resources getTheme() {
        return theme;
    }

    public void setTheme(Resources theme) {
        this.theme = theme;
    }
    
    

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);
        
        
        theme = UIManager.initFirstTheme("/theme"); 
        
        // baseEmp = UIManager.initFirstTheme("/theme");
        // theme = UIManager.initFirstTheme("/theme_1");
        
         
         //theme = UIManager.initNamedTheme("/theme_1","Theme");
         //baseEmp = UIManager.initNamedTheme("/theme","baseEmp");
         

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
       Hashtable themeData = theme.getTheme("Theme");
       UIManager.getInstance().setThemeProps(themeData);
      
       new SplashForm().show();
      //new StatsForm(theme).show();
      //new InboxForm(theme).show();
      //new DetailsForm(theme).show(); 
      //new WalkthruForm(theme).show();
      //new TrendingForm(theme).show();
      //new InboxForm(theme).show();
      //new BaseAgentRHForm11().show();
      //new EmployerForm(baseEmp).show();
      //new HomeForm().show();
              

               
    }
    
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
